### GET /api/tasks
GET http://localhost:3000/api/tasks

### GET /api/tasks/:id
GET http://localhost:3000/api/tasks/1

### POST /api/tasks
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Task 2",
  "description": "Task 2 description",
  "limitDate": "2023-07-01T00:00:00.000Z",
  "status": "Pendiente",
  "priority": 2,
  "category": "Category 1"
}

### PATCH /api/tasks/:id
PATCH http://localhost:3000/api/tasks/2
Content-Type: application/json

{
  "description": "Description updated"
}

### DELETE /api/tasks/:id
DELETE http://localhost:3000/api/tasks/1